build: prob1.c
	gcc -Wall prob1.c -o prob1
	gcc -Wall prob3.c -o prob3
	gcc -Wall prob2.c -o prob2

run-p1:
	./prob1

run-p2:
	./prob2

run-p3:
	./prob3

clean:
	rm -f prob1
	rm -f prob2
	rm -f prob3
